### ISSUE TITLE
Video does not start at https://www.renault.si/kampanje/renaulution.html

### ISSUE THREAD

**Issue by crssi** [da2x/youtube-nocookie#2]
Video does not start at `https://www.renault.si/kampanje/renaulution.html` when extension is enabled.

Cheers

**Comment by da2x** [comment]
This is unfixable. They’re using a completely custom outer player wrapped around the YouTube embed player.

The outer player sends a message to the iframe, assuming it to be youtube.com instead of youtube-nocookie.com. There’s no way to intercept such a message nor to fool the browser to thing a frame belongs to a different origin.

The best fix I can think of is a whitelist, but that would require the user to realize what is happening and intervene to disable the extension.

**Comment by crssi** [comment]
Thank you anyway. 
Cheers
